(() => {
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=s=>/^(https:\/\/|assets\/|[a-z-]+\.html(?:[?#].*)?$)/i.test(s)?esc(s):'#';
let content,style='Safari';
function packing(){document.getElementById('packing-list').innerHTML=content.packing[style].map(s=>'<li>'+esc(s)+'</li>').join('');document.querySelectorAll('[data-pack]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.pack===style)));}
function section(s){return '<section class="tg-section" id="'+esc(s.id)+'"><div class="'+(s.image?'tg-split':'')+'">'+(s.image?'<img src="'+safe(s.image)+'" alt="'+esc(s.imageAlt)+'" loading="lazy" width="680" height="440">':'')+'<div><span class="tg-eyebrow">'+esc(s.label)+'</span><h2>'+esc(s.title)+'</h2><p>'+esc(s.description)+'</p><ul class="tg-checks">'+s.checklist.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul><p class="tg-links">'+s.links.map(l=>'<a href="'+safe(l.url)+'"'+(l.url.startsWith('https:')?' target="_blank" rel="noopener"':'')+'>'+esc(l.label)+' →</a>').join('')+'</p>'+(s.reviewed?'<p class="tg-small">Official guidance last reviewed: '+esc(s.reviewed)+'. Recheck before departure.</p>':'')+'</div></div></section>';}
window.loadTravelGuideContent().then(data=>{
content=data;document.getElementById('guide-sections').innerHTML=data.sections.filter(s=>['arrival','money'].includes(s.id)).map(section).join('');document.getElementById('guide-later').innerHTML=data.sections.filter(s=>['culture','transport'].includes(s.id)).map(section).join('');document.getElementById('guide-faqs').innerHTML=data.faqs.map(f=>'<details><summary>'+esc(f.question)+'</summary><p>'+esc(f.answer)+'</p></details>').join('');packing();
document.querySelectorAll('[data-pack]').forEach(b=>b.addEventListener('click',()=>{style=b.dataset.pack;packing();}));
document.getElementById('download-pack').addEventListener('click',()=>{const text='CENTURY EXPEDITIONS — TANZANIA TRAVEL GUIDE\n'+style.toUpperCase()+' PACKING CHECKLIST\n\n'+content.packing[style].map(s=>'[ ] '+s).join('\n')+'\n\nConfirm baggage limits and specialist equipment with your operator.\nvisit@century-adventures.com';const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='tanzania-'+style.toLowerCase()+'-packing.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
}).catch(()=>{document.getElementById('guide-sections').textContent='The guide could not load. Please refresh or contact visit@century-adventures.com.';});
document.querySelectorAll('.tg-nav a, .tg-hero a[href^="#"]').forEach(link=>link.addEventListener('click',e=>{const target=document.querySelector(link.getAttribute('href'));if(!target)return;e.preventDefault();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});history.replaceState(null,'',link.getAttribute('href'));document.querySelectorAll('.tg-nav a').forEach(a=>a.setAttribute('aria-current',String(a.getAttribute('href')===link.getAttribute('href'))));target.tabIndex=-1;target.focus({preventScroll:true});}));
})();
